<?php
//create_topic.php
include 'connect.php';
include 'header.php';

echo '<h2>Create a new topic</h2>';
if($_SESSION['signed_in'] == false)
{
    //user is not signed in
    echo 'Please sign in before posting';
}
else
{
    if($_SERVER['REQUEST_METHOD'] != 'POST')
    {
        //the form hasnt been posted yet...get category info 
        $sql = "select cat_id, cat_name, cat_desc
                from FORUM.categories";

        $result = mysql_query($sql);

	// Nothing returned from query.
        if(!$result)
        {
            echo 'Oops. Something went wrong. Please try again.';
        }
        else
        {
            // Check if there are any categories.
            if(mysql_num_rows($result) == 0)
            {
                // No categories exist yet. If lvl 1 user, alert them.
                if($_SESSION['user_level'] == 1)
                {
                    echo 'There are no categories yet. There must be a category to make a new topic';
                }
                else
                {
                    echo 'Unable to post right now. Please try later';
                }
            }
            else
            {
                // Post the form to create a new topic.
                echo '<form method="post" action="">
                      Subject<input type="text" name="topic_subject" />
                      Category ';
                echo '<select name="topic_cat">';
                // Populate dropdown menu.
                while($row = mysql_fetch_assoc($result)) 
                {
                    $cat_id = $row['cat_id'];;
                    $cat_name = $row['cat_name'];
                    echo '<option value="' . $cat_id . '">' . $cat_name .  '</option>';
                }

                echo '</select>';

                echo 'Message: <textarea name="post_content" /></textarea>
			       <input type="submit" value="Create Topic" />
                      </form>';                      
            }
        }
    }
    else
    {
        // Start the transaction; will be inserting into 2 tables, topic and category.
        $query = "BEGIN WORK;";
        $result = mysql_query($query);

        if(!$result)
	{
            // Query failed.
            echo 'Something went wrong when creating your topic. Please try again';
	}
	else
	{
            // Inserts new query topic into topics table.
	    $sql = "INSERT INTO FORUM.topics(topic_subj, topic_date, topic_cat, topic_by)
	    	    VALUES('" . mysql_real_escape_string($_POST['topic_subject']) . "', NOW(),'" .
 	            mysql_real_escape_string($_POST['topic_cat']) . "', '" . $_SESSION['user_id'] . "')";

            // Try first query.
            $result = mysql_query($sql);
          
	    if(!$result)
            {
                // Something went wrong. Rollback changes.
                $sql = "ROLLBACK;";
                $result = mysql_query($sql); 
            }
            else
	    {
                // First query worked, do second query.

                // mysql_insert_id(): gets ID generated for the auto increment column 
                // generated by previous query
	 	$topicID = mysql_insert_id();	

                // Second query; Insert new post in to table.
                $sql = "INSERT INTO FORUM.posts(post_content, post_date, post_topic, post_by)
                        VALUES('" . mysql_real_escape_string($_POST['post_content']) . "', 
                        NOW(), '" . 
                        $topicID . "', '" . 
                        mysql_real_escape_string($_SESSION['user_id']) . "')"; 

                // Try second query.
                $result = mysql_query($sql);
                
                if(!$result)
		{
                    // Something went wrong. Rollback changes.
                    echo 'Unable to create post. Please try again.';
		    $sql = "ROLLBACK;";
                    mysql_query($sql);
		}
                else
		{
		    // Queries both worked. Commit changes.
                    $sql = "COMMIT;";
                    mysql_query($sql);
                      
                    // Post created succesfully. 
                    echo 'Post succesfully created. <a href="topic.php?id="' . $topicID . '">Go to Topics</a>';
		}
                
            }
	}
    }
}

include 'footer.php';
